### ISSUE TITLE
Test it against new unseen and unlabeled data

### ISSUE THREAD

**Issue by Jurafsky21** [chiayewken/Span-ASTE#13]
Hello,
I have trained the model on my own data and save the parameters in the jsonnet file. I would like to use it now with test file that is not annotated/labeled. How should I do that? When I try to put my unlabeled data as a test.txt seems not accepting a not unlabeled file. I suppose it tries to start an evaluation but of course it can't since there is no data for comparison.

Is there anything I need to do/change in the code for this? 

Thank you

**Comment by Jurafsky21** [comment]
When I try to run it against a test sample with no labels I encounter this:

```
DEVICE=0
{
  "names": "sample",
  "seeds": [
    0
  ],
  "sep": ",",
  "name_out": "results",
  "kwargs": {
    "trainer__cuda_device": 0,
    "trainer__num_epochs": 10,
    "trainer__checkpointer__num_serialized_models_to_keep": 1,
    "model__span_extractor_type": "endpoint",
    "model__modules__relation__use_single_pool": false,
    "model__relation_head_type": "proper",
    "model__use_span_width_embeds": true,
    "model__modules__relation__use_distance_embeds": true,
    "model__modules__relation__use_pair_feature_multiply": false,
    "model__modules__relation__use_pair_feature_maxpool": false,
    "model__modules__relation__use_pair_feature_cls": false,
    "model__modules__relation__use_span_pair_aux_task": false,
    "model__modules__relation__use_span_loss_for_pruners": false,
    "model__loss_weights__ner": 1.0,
    "model__modules__relation__spans_per_word": 0.5,
    "model__modules__relation__neg_class_weight": -1
  },
  "root": "aste/data/triplet_data"
}
{
  "root": "/content/Span-ASTE/aste/data/triplet_data/sample",
  "train_kwargs": {
    "seed": 0,
    "trainer__cuda_device": 0,
    "trainer__num_epochs": 10,
    "trainer__checkpointer__num_serialized_models_to_keep": 1,
    "model__span_extractor_type": "endpoint",
    "model__modules__relation__use_single_pool": false,
    "model__relation_head_type": "proper",
    "model__use_span_width_embeds": true,
    "model__modules__relation__use_distance_embeds": true,
    "model__modules__relation__use_pair_feature_multiply": false,
    "model__modules__relation__use_pair_feature_maxpool": false,
    "model__modules__relation__use_pair_feature_cls": false,
    "model__modules__relation__use_span_pair_aux_task": false,
    "model__modules__relation__use_span_loss_for_pruners": false,
    "model__loss_weights__ner": 1.0,
    "model__modules__relation__spans_per_word": 0.5,
    "model__modules__relation__neg_class_weight": -1
  },
  "path_config": "/content/Span-ASTE/training_config/aste.jsonnet",
  "repo_span_model": "/content/Span-ASTE",
  "output_dir": "model_outputs/aste_sample_c7b00b66bf7ec669d23b80879fda043d",
  "model_path": "models/aste_sample_c7b00b66bf7ec669d23b80879fda043d/model.tar.gz",
  "data_name": "sample",
  "task_name": "aste"
}
# of original triplets:  11
# of triplets for current setup:  11
# of original triplets:  7
# of triplets for current setup:  7
Traceback (most recent call last):
  File "/usr/lib/python3.7/pdb.py", line 1699, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.7/pdb.py", line 1568, in _runscript
    self.run(statement)
  File "/usr/lib/python3.7/bdb.py", line 578, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/content/Span-ASTE/aste/main.py", line 1, in <module>
    import json
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/content/Span-ASTE/aste/main.py", line 278, in main
    scores = main_single(p, overwrite=True, seed=seeds[i], **kwargs)
  File "/content/Span-ASTE/aste/main.py", line 254, in main_single
    trainer.train(overwrite=overwrite)
  File "/content/Span-ASTE/aste/main.py", line 185, in train
    self.setup_data()
  File "/content/Span-ASTE/aste/main.py", line 177, in setup_data
    data.load()
  File "aste/data_utils.py", line 214, in load
    opinion_offset=self.opinion_offset,
  File "aste/evaluation.py", line 165, in read_inst
    o_output = line[2].split()  # opinion
IndexError: list index out of range
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /content/Span-ASTE/aste/evaluation.py(165)read_inst()
-> o_output = line[2].split()  # opinion
(Pdb) 
```

**Comment by Jurafsky21** [comment]
There was an error in the labeling that's why it was not working. To make it work on unseen data, it seems to need the same structure with labels but the labels can be fake. Of course the final report won't be reflecting exactly the performance of the system since the data used has not been labeled and therefore no comparison with gold standard can be done.
